project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "sudo_masochist_"
    #change to false and is possible to have a gif
    #logo: images/test_gig.gif
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sudo-masochist/
        target: _blank
      - icon: reddit
        href: https://www.reddit.com/user/sudo_masochist/
        target: _blank
    google-analytics: "G-3ZQ33TPE3P"
format:
  html:
    theme:
      - test.scss

editor: visual

